version: '3'

services:
  web:
    build: .
    command: bash -c "python manage.py runserver 0.0.0.0:8000"
    container_name: impartnewspoint_container
    restart: always
    volumes:
      - .:/django_api
    ports:
      - "8000:8000"
    networks:
      - postgres

networks:
  postgres:
    driver: bridge